id: unauth-esphome

info:
  name: ESPHome Web Server access - Unauthenticated Access
  author: pussycat0x
  severity: high
  description: |
    ESPHome is a powerful smart home devices with simple YAML configuration.
  reference:
    - https://esphome.io/components/web_server/
  metadata:
    verified: true
    max-request: 1
    shodan-query: http.title:"ESPHome"
  tags: esphome,iot,unauth,misconfig

http:
  - method: GET
    path:
      - "{{BaseURL}}"

    matchers:
      - type: dsl
        dsl:
          - 'status_code == 200'
          - 'contains(body, "<title>Dashboard - ESPHome")'
        condition: and
