id: nextjs-vite-public-env-exposure
info:
  name: Next.js / Vite public ENV exposure (incl. Supabase URL/Anon Key)
  author: Hamza Sahin (@hamzasahin61)
  severity: medium
  description: |
    Detects public environment variables exposed to the client in Next.js (__NEXT_DATA__.env)
    and Vite/window runtime configs. Matches generic NEXT_PUBLIC_* / VITE_* and focused
    Supabase URL/Anon key patterns.
  reference:
    - https://nextjs.org/docs/app/building-your-application/configuring/environment-variables
    - https://vitejs.dev/guide/env-and-mode.html
    - https://supabase.com/docs/guides/api#api-keys
  tags: exposure,env,nextjs,vite,supabase,config,web

requests:
  - method: GET
    path:
      - "{{BaseURL}}/"
      - "{{BaseURL}}/index.html"
    stop-at-first-match: true

    matchers-condition: or
    matchers:
      # Focused Supabase leaks
      - type: regex
        part: body
        regex:
          - '(?i)"NEXT_PUBLIC_SUPABASE_URL"\s*:\s*"https?://[a-z0-9\.\-:/]+"'
          - '(?i)"NEXT_PUBLIC_SUPABASE_ANON_KEY"\s*:\s*"[A-Za-z0-9\.\-_]{20,}"'
          - '(?i)\bVITE_SUPABASE_URL\b"\s*:\s*"https?://[a-z0-9\.\-:/]+"'
          - '(?i)\bVITE_SUPABASE_ANON_KEY\b"\s*:\s*"[A-Za-z0-9\.\-_]{20,}"'
          - '(?i)window\.__env\s*=\s*\{[^}]*?(SUPABASE_(URL|ANON_KEY))[^}]*?\}'

      # Generic Next.js public env container
      - type: regex
        part: body
        regex:
          - '(?i)__NEXT_DATA__.*?"env"\s*:\s*\{[^}]*?NEXT_PUBLIC_[A-Z0-9_]{2,}'

      # Generic Vite public env pairs
      - type: regex
        part: body
        regex:
          - '(?i)\bVITE_[A-Z0-9_]{2,}"\s*:\s*"[^"]{3,}'

    extractors:
      - type: regex
        part: body
        name: supabase_url
        group: 1
        regex:
          - '(?i)"NEXT_PUBLIC_SUPABASE_URL"\s*:\s*"(https?://[a-z0-9\.\-:/]+)"'
          - '(?i)\bVITE_SUPABASE_URL\b"\s*:\s*"(https?://[a-z0-9\.\-:/]+)"'

      - type: regex
        part: body
        name: supabase_anon_key
        group: 1
        regex:
          - '(?i)"NEXT_PUBLIC_SUPABASE_ANON_KEY"\s*:\s*"([A-Za-z0-9\.\-_]{20,})"'
          - '(?i)\bVITE_SUPABASE_ANON_KEY\b"\s*:\s*"([A-Za-z0-9\.\-_]{20,})"'

      - type: regex
        part: body
        name: public_env
        regex:
          - '(?i)"(NEXT_PUBLIC_[A-Z0-9_]{2,})"\s*:\s*"([^"]{3,})"'
          - '(?i)"(VITE_[A-Z0-9_]{2,})"\s*:\s*"([^"]{3,})"'
